-- MySQL Script generated by MySQL Workbench
-- Tue Jul 31 13:26:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Id_Persona` INT NOT NULL,
  `P_Nombre` VARCHAR(45) NOT NULL,
  `S_Nombre` VARCHAR(45) NOT NULL,
  `P_Apellido` VARCHAR(45) NOT NULL,
  `S_Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Num_Cedula` INT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`Id_Persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `Id_Telefono` INT NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Id_Persona` INT NOT NULL,
  PRIMARY KEY (`Id_Telefono`),
  INDEX `fk_Telefono_Persona_idx` (`Id_Persona` ASC),
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`Id_Persona`)
    REFERENCES `mydb`.`Persona` (`Id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `Id_Departamento` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `Id_Municipio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_Departamento` INT NOT NULL,
  PRIMARY KEY (`Id_Municipio`),
  INDEX `fk_Municipio_Departamento1_idx` (`Id_Departamento` ASC),
  CONSTRAINT `fk_Municipio_Departamento1`
    FOREIGN KEY (`Id_Departamento`)
    REFERENCES `mydb`.`Departamento` (`Id_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `Id_Ciudad` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_Municipio` INT NOT NULL,
  PRIMARY KEY (`Id_Ciudad`),
  INDEX `fk_Ciudad_Municipio1_idx` (`Id_Municipio` ASC),
  CONSTRAINT `fk_Ciudad_Municipio1`
    FOREIGN KEY (`Id_Municipio`)
    REFERENCES `mydb`.`Municipio` (`Id_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colonia` (
  `Id_Colonia` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_Ciudad` INT NOT NULL,
  PRIMARY KEY (`Id_Colonia`),
  INDEX `fk_Colonia_Ciudad1_idx` (`Id_Ciudad` ASC),
  CONSTRAINT `fk_Colonia_Ciudad1`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `mydb`.`Ciudad` (`Id_Ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `Id_Direccion` INT NOT NULL,
  `Bloque` VARCHAR(45) NOT NULL,
  `Casa` VARCHAR(45) NOT NULL,
  `Id_Persona` INT NULL,
  `Id_Colonia` INT NOT NULL,
  PRIMARY KEY (`Id_Direccion`),
  INDEX `fk_Direccion_Persona1_idx` (`Id_Persona` ASC),
  INDEX `fk_Direccion_Colonia1_idx` (`Id_Colonia` ASC),
  CONSTRAINT `fk_Direccion_Persona1`
    FOREIGN KEY (`Id_Persona`)
    REFERENCES `mydb`.`Persona` (`Id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Colonia1`
    FOREIGN KEY (`Id_Colonia`)
    REFERENCES `mydb`.`Colonia` (`Id_Colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Id_Cliente` INT NOT NULL,
  `Fecha_Registro` VARCHAR(45) NOT NULL,
  `Id_Persona` INT NOT NULL,
  PRIMARY KEY (`Id_Cliente`),
  INDEX `fk_Cliente_Persona1_idx` (`Id_Persona` ASC),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Id_Persona`)
    REFERENCES `mydb`.`Persona` (`Id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `Id_Cargo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `Id_Empleado` INT NOT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `Id_Persona` INT NOT NULL,
  `Id_Cargo` INT NOT NULL,
  PRIMARY KEY (`Id_Empleado`),
  INDEX `fk_Empleado_Persona1_idx` (`Id_Persona` ASC),
  INDEX `fk_Empleado_Cargo1_idx` (`Id_Cargo` ASC),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Id_Persona`)
    REFERENCES `mydb`.`Persona` (`Id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Cargo1`
    FOREIGN KEY (`Id_Cargo`)
    REFERENCES `mydb`.`Cargo` (`Id_Cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
  `idihaerfijsw` INT NOT NULL,
  PRIMARY KEY (`idihaerfijsw`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autores` (
  `Id_Autores` INT NOT NULL,
  `Id_Persona` INT NOT NULL,
  PRIMARY KEY (`Id_Autores`),
  INDEX `fk_Autores_Persona1_idx` (`Id_Persona` ASC),
  CONSTRAINT `fk_Autores_Persona1`
    FOREIGN KEY (`Id_Persona`)
    REFERENCES `mydb`.`Persona` (`Id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Id_Producto` INT NOT NULL,
  `Precio_Compra` FLOAT NOT NULL,
  `Precio_Venta` FLOAT NOT NULL,
  `Estado` TINYINT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libros` (
  `Id_Libros` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Paginas` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Producto_Id_Producto` INT NOT NULL,
  `Municipio_Id_Municipio` INT NOT NULL,
  PRIMARY KEY (`Id_Libros`),
  INDEX `fk_Libros_Producto1_idx` (`Producto_Id_Producto` ASC),
  INDEX `fk_Libros_Municipio1_idx` (`Municipio_Id_Municipio` ASC),
  CONSTRAINT `fk_Libros_Producto1`
    FOREIGN KEY (`Producto_Id_Producto`)
    REFERENCES `mydb`.`Producto` (`Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_Municipio1`
    FOREIGN KEY (`Municipio_Id_Municipio`)
    REFERENCES `mydb`.`Municipio` (`Id_Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `Id_Genero` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libros_Genero` (
  `Id_Libros` INT NOT NULL,
  `Id_Genero` INT NOT NULL,
  PRIMARY KEY (`Id_Libros`, `Id_Genero`),
  INDEX `fk_Libros_has_Genero_Genero1_idx` (`Id_Genero` ASC),
  INDEX `fk_Libros_has_Genero_Libros1_idx` (`Id_Libros` ASC),
  CONSTRAINT `fk_Libros_has_Genero_Libros1`
    FOREIGN KEY (`Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Genero_Genero1`
    FOREIGN KEY (`Id_Genero`)
    REFERENCES `mydb`.`Genero` (`Id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autores_Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autores_Libros` (
  `Id_Autores` INT NOT NULL,
  `Id_Libros` INT NOT NULL,
  PRIMARY KEY (`Id_Autores`, `Id_Libros`),
  INDEX `fk_Autores_has_Libros_Libros1_idx` (`Id_Libros` ASC),
  INDEX `fk_Autores_has_Libros_Autores1_idx` (`Id_Autores` ASC),
  CONSTRAINT `fk_Autores_has_Libros_Autores1`
    FOREIGN KEY (`Id_Autores`)
    REFERENCES `mydb`.`Autores` (`Id_Autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autores_has_Libros_Libros1`
    FOREIGN KEY (`Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `Id_Editorial` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros_Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libros_Editorial` (
  `Id_Libros` INT NOT NULL,
  `Id_Editorial` INT NOT NULL,
  PRIMARY KEY (`Id_Libros`, `Id_Editorial`),
  INDEX `fk_Libros_has_Editorial_Editorial1_idx` (`Id_Editorial` ASC),
  INDEX `fk_Libros_has_Editorial_Libros1_idx` (`Id_Libros` ASC),
  CONSTRAINT `fk_Libros_has_Editorial_Libros1`
    FOREIGN KEY (`Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Editorial_Editorial1`
    FOREIGN KEY (`Id_Editorial`)
    REFERENCES `mydb`.`Editorial` (`Id_Editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cubiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cubiculo` (
  `IdCubiculo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Libros_Id_Libros` INT NOT NULL,
  PRIMARY KEY (`IdCubiculo`),
  INDEX `fk_Cubiculo_Libros1_idx` (`Libros_Id_Libros` ASC),
  CONSTRAINT `fk_Cubiculo_Libros1`
    FOREIGN KEY (`Libros_Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estante` (
  `Id_Estante` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cubiculo_IdCubiculo` INT NOT NULL,
  PRIMARY KEY (`Id_Estante`),
  INDEX `fk_Estante_Cubiculo1_idx` (`Cubiculo_IdCubiculo` ASC),
  CONSTRAINT `fk_Estante_Cubiculo1`
    FOREIGN KEY (`Cubiculo_IdCubiculo`)
    REFERENCES `mydb`.`Cubiculo` (`IdCubiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `Id_Biblioteca` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_Estante` INT NOT NULL,
  PRIMARY KEY (`Id_Biblioteca`),
  INDEX `fk_Biblioteca_Estante1_idx` (`Id_Estante` ASC),
  CONSTRAINT `fk_Biblioteca_Estante1`
    FOREIGN KEY (`Id_Estante`)
    REFERENCES `mydb`.`Estante` (`Id_Estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamos` (
  `Id_Prestamos` INT NOT NULL,
  `Fecha_Prestado` DATE NOT NULL,
  `Fecha_Entrega` DATE NOT NULL,
  `Cantidad` INT NOT NULL,
  `Id_Cliente` INT NOT NULL,
  `Id_Libros` INT NOT NULL,
  PRIMARY KEY (`Id_Prestamos`),
  INDEX `fk_Prestamos_Cliente1_idx` (`Id_Cliente` ASC),
  INDEX `fk_Prestamos_Libros1_idx` (`Id_Libros` ASC),
  CONSTRAINT `fk_Prestamos_Cliente1`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamos_Libros1`
    FOREIGN KEY (`Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forma_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma_Pago` (
  `Id_Forma_Pago` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Forma_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Impuesto` (
  `Id_Impuesto` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Monto` FLOAT NOT NULL,
  PRIMARY KEY (`Id_Impuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `Id_Factura` INT NOT NULL,
  `Fecha` DATE NULL,
  `Id_Empleado` INT NOT NULL,
  `Id_Cliente` INT NOT NULL,
  `Forma_Pago_Id_Forma_Pago` INT NOT NULL,
  `Impuesto_Id_Impuesto` INT NOT NULL,
  PRIMARY KEY (`Id_Factura`),
  INDEX `fk_Factura_Empleado1_idx` (`Id_Empleado` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`Id_Cliente` ASC),
  INDEX `fk_Factura_Forma_Pago1_idx` (`Forma_Pago_Id_Forma_Pago` ASC),
  INDEX `fk_Factura_Impuesto1_idx` (`Impuesto_Id_Impuesto` ASC),
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`Id_Empleado`)
    REFERENCES `mydb`.`Empleado` (`Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Forma_Pago1`
    FOREIGN KEY (`Forma_Pago_Id_Forma_Pago`)
    REFERENCES `mydb`.`Forma_Pago` (`Id_Forma_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Impuesto1`
    FOREIGN KEY (`Impuesto_Id_Impuesto`)
    REFERENCES `mydb`.`Impuesto` (`Id_Impuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura_Detalle` (
  `Id_Factura_Detalle` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `Producto_Id_Producto` INT NOT NULL,
  `Factura_Detalle_Id_Factura` INT NOT NULL,
  PRIMARY KEY (`Id_Factura_Detalle`),
  INDEX `fk_Factura_Producto1_idx` (`Producto_Id_Producto` ASC),
  INDEX `fk_Factura_Factura_Detalle1_idx` (`Factura_Detalle_Id_Factura` ASC),
  CONSTRAINT `fk_Factura_Producto1`
    FOREIGN KEY (`Producto_Id_Producto`)
    REFERENCES `mydb`.`Producto` (`Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Factura_Detalle1`
    FOREIGN KEY (`Factura_Detalle_Id_Factura`)
    REFERENCES `mydb`.`Factura` (`Id_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuentos` (
  `Id_Descuentos` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Porcenatje` FLOAT NOT NULL,
  PRIMARY KEY (`Id_Descuentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuentos_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuentos_Factura` (
  `Id_Descuentos` INT NOT NULL,
  `Id_Factura` INT NOT NULL,
  PRIMARY KEY (`Id_Descuentos`, `Id_Factura`),
  INDEX `fk_Descuentos_has_Factura_Factura1_idx` (`Id_Factura` ASC),
  INDEX `fk_Descuentos_has_Factura_Descuentos1_idx` (`Id_Descuentos` ASC),
  CONSTRAINT `fk_Descuentos_has_Factura_Descuentos1`
    FOREIGN KEY (`Id_Descuentos`)
    REFERENCES `mydb`.`Descuentos` (`Id_Descuentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Descuentos_has_Factura_Factura1`
    FOREIGN KEY (`Id_Factura`)
    REFERENCES `mydb`.`Factura` (`Id_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_Producto` (
  `Id_Categoria_Producto` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Categoria_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega_Tardia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega_Tardia` (
  `Id_Entrega_Tardia` INT NOT NULL,
  `Fecha_Estipulada` DATE NOT NULL,
  `Fecha_Entregado` DATE NOT NULL,
  `Id_Cliente` INT NOT NULL,
  `Id_Libros` INT NOT NULL,
  `Monto` FLOAT NOT NULL,
  PRIMARY KEY (`Id_Entrega_Tardia`),
  INDEX `fk_Entrega_Tardia_Cliente1_idx` (`Id_Cliente` ASC),
  INDEX `fk_Entrega_Tardia_Libros1_idx` (`Id_Libros` ASC),
  CONSTRAINT `fk_Entrega_Tardia_Cliente1`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_Tardia_Libros1`
    FOREIGN KEY (`Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movimiento` (
  `Fecha` DATE NOT NULL,
  `Id_Movimiento` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Empleado_Id_Empleado` INT NOT NULL,
  `Biblioteca_Id_Biblioteca` INT NOT NULL,
  PRIMARY KEY (`Id_Movimiento`),
  INDEX `fk_Movimiento_Empleado1_idx` (`Empleado_Id_Empleado` ASC),
  INDEX `fk_Movimiento_Biblioteca1_idx` (`Biblioteca_Id_Biblioteca` ASC),
  CONSTRAINT `fk_Movimiento_Empleado1`
    FOREIGN KEY (`Empleado_Id_Empleado`)
    REFERENCES `mydb`.`Empleado` (`Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_Biblioteca1`
    FOREIGN KEY (`Biblioteca_Id_Biblioteca`)
    REFERENCES `mydb`.`Biblioteca` (`Id_Biblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle` (
  `Cantidad` INT NOT NULL,
  `Movimiento_Id_Movimiento` INT NOT NULL,
  `Libros_Id_Libros` INT NOT NULL,
  `Id_Detalle` INT NOT NULL,
  INDEX `fk_Detalle_Movimiento1_idx` (`Movimiento_Id_Movimiento` ASC),
  INDEX `fk_Detalle_Libros1_idx` (`Libros_Id_Libros` ASC),
  PRIMARY KEY (`Id_Detalle`),
  CONSTRAINT `fk_Detalle_Movimiento1`
    FOREIGN KEY (`Movimiento_Id_Movimiento`)
    REFERENCES `mydb`.`Movimiento` (`Id_Movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Libros1`
    FOREIGN KEY (`Libros_Id_Libros`)
    REFERENCES `mydb`.`Libros` (`Id_Libros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
